<#import "/templates/guide.adoc" as tmpl>
<#import "/templates/links.adoc" as links>
<#import "/templates/profile.adoc" as profile>

<@tmpl.guide
title="Multi-AZ Deployments"
summary="Deploy Keycloak across multiple availability-zones in Kubernetes." >


== When to use a multi-az setup
The multi-az deployment capabilities of {project_name} are targeted at use cases that:

* Deploy a single Kubernetes cluster for all {project_name} deployments
* Require the ability to withstand availability-zone failures
* Fit within a defined user and request count.
* Can accept the impact of periodic outages.

<@profile.ifCommunity>
[#multi-az-tested-configuration]
== Tested Configuration

We regularly test {project_name} with the following configuration:
</@profile.ifCommunity>
<@profile.ifProduct>
[#multi-az-supported-configuration]
== Supported Configuration
</@profile.ifProduct>

* An Openshift cluster deployed across three availability-zones
** Provisioned with https://www.redhat.com/en/technologies/cloud-computing/openshift/aws[Red Hat OpenShift Service on AWS] (ROSA),
<@profile.ifProduct>
either ROSA HCP or ROSA classic.
</@profile.ifProduct>
<@profile.ifCommunity>
using ROSA HCP.
</@profile.ifCommunity>

** At least one worker node for each availability-zone
** OpenShift version
<@profile.ifProduct>
4.17 (or later).
</@profile.ifProduct>
<@profile.ifCommunity>
4.17.
</@profile.ifCommunity>

* Amazon Aurora PostgreSQL database
** High availability with a primary DB instance in one Availability Zone, and a synchronously replicated reader in the second Availability Zone
** Version ${properties["aurora-postgresql.version"]}

<#include "/high-availability/partials/configuration-disclaimer.adoc" />

Read more on each item in the <@links.ha id="multi-az-building-blocks" /> {section}.

[#multi-az-load]
<#include "/high-availability/partials/tested-load.adoc" />

[#multi-az-limitations]
== Limitations

<@profile.ifCommunity>
Even with the additional redundancy of three availability-zones, downtimes can still occur:
</@profile.ifCommunity>

* During upgrades of {project_name}
** Enable <@links.server id="update-compatibility" anchor="rolling-updates-for-patch-releases" /> to minimize downtime

For more details on limitations see the <@links.ha id="multi-az-concepts" /> {section}.

== Next steps

The different {sections} introduce the necessary concepts and building blocks.
For each building block, a blueprint shows how to set a fully functional example.
Additional performance tuning and security hardening are still recommended when preparing a production setup.

<@profile.ifCommunity>
== Concept and building block overview

* <@links.ha id="multi-az-concepts" />
* <@links.ha id="multi-az-building-blocks" />
* <@links.ha id="multi-az-concepts-database-connections" />
* <@links.ha id="multi-az-concepts-threads" />
* <@links.ha id="multi-az-concepts-memory-and-cpu-sizing" />

== Blueprints for building blocks
* <@links.ha id="multi-az-deploy-aurora" />
* <@links.ha id="multi-az-deploy-keycloak" />
</@profile.ifCommunity>

</@tmpl.guide>
